services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular19-app
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
